[tasks.web]
command = "bevy"
args = ["run", "--features", "web", "--release", "web", "--wasm-opt", "false"]


[tasks.build-web]
command = "bevy"
args = ["build", "--features", "web", "--release", "web"]

[tasks.webgpu]
command = "bevy"
args = ["run", "--features", "webgpu", "web"]


[tasks.build-webgpu]
command = "bevy"
args = ["build", "--features", "webgpu", "--release", "web"]


[tasks.run]
command = "cargo"
args = ["run", "--features", "native"]

[tasks.dev]
command = "cargo"
args = ["run", "--features", "dev native"]

[tasks.dyn]
command = "cargo"
args = ["run", "--features", "dynamic_linking native"]

[tasks.dyn-dev]
command = "cargo"
args = ["run", "--features", "dev dynamic_linking native"]


[tasks.build-release]
command = "cargo"
args = ["build", "--features", "native", "--release"]


[tasks.run-release]
command = "cargo"
args = ["run", "--features", "native", "--release"]

[tasks.dhot]
command = "dx"
args = ["serve", "--features", "dev hot native", "--hot-patch"]
