[tasks.web]
command = "trunk"
args = ["serve", "--release", "--features", "web"]

[tasks.chrome]
command = "trunk"
args = ["serve", "--release", "--features", "webgpu"]


[tasks.run]
command = "cargo"
args = ["run", "--features", "native"]

[tasks.dev]
command = "cargo"
args = ["run", "--features", "dev native"]

[tasks.dyn]
command = "cargo"
args = ["run", "--features", "dynamic_linking native"]

[tasks.dyn-dev]
command = "cargo"
args = ["run", "--features", "dev dynamic_linking native"]


[tasks.release]
command = "cargo"
args = ["build", "--features", "native", "--profile", "release-dist"]

[tasks.brp]
command = "cargo"
args = ["run", "--features", "dev", "--bin", "brp"]

[tasks.dhot]
command = "dx"
args = ["serve", "--features", "dev hot native", "--hot-patch"]
